[package]
name = "NFTMarketplace"
version = "0.1.0"

[addresses]
NFTMarketplace = "0x75ddf648ace075a4dfb356d3c5cd2cb4e61249d7273d3a5491e0ee486f26791f"
aptos_framework = "0x1"
primitives = "0xCAFE"

[dependencies]
AptosFramework = { local = "./aptos-core/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "./aptos-core/aptos-move/framework/aptos-stdlib" }
MoveStdlib = { local = "./aptos-core/aptos-move/framework/move-stdlib" }