[package]
name = "fuzzer"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
aptos-framework = { workspace = true }
aptos-types = { workspace = true }
arbitrary = { workspace = true }
base64 = "0.21.7"
bcs = { workspace = true }
clap = "4.5.20"
csv = "1.3.0"
dearbitrary = { workspace = true }
hex = "0.4.3"
move-binary-format = { workspace = true, features = ["fuzzing"] }
move-core-types = { workspace = true, features = ["fuzzing"] }
sha2 = { workspace = true }
